services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./.env
    environment:
      DATABASE_URL: mongodb://mongo:27017/${MONGO_INITDB_DATABASE}
      PYTHONPATH: /app
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

  fastapi:
    container_name: api
    build:
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

volumes:
  mongo:
